/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID as string;
export const publicAnonKey = process.env.SUPABASE_PUBLIC_ANON_KEY as string;
if (!publicAnonKey) {
  throw new Error("Missing environment variable: SUPABASE_PUBLIC_ANON_KEY");
}