/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mqwlrpivluluytlmvcrc"
export const publicAnonKey = process.env.SUPABASE_PUBLIC_ANON_KEY as string;
if (!publicAnonKey) {
  throw new Error("Missing environment variable: SUPABASE_PUBLIC_ANON_KEY");
}